#!/bin/bash

conda activate spddsmbn-venv
cd /data/zchen/Released_Code/SPDMLR

#SPDNet-SPDMLR-LEM
python SPDNet-MLR_Kfolds.py -m\
  dataset=HDM05\
  dataset.path=/data/zchen/Datasets/HDM05/spd_data_1e-6_1000000/\
  fit.folds=10\
  fit.epochs=150\
  fit.cycle=50\
  nnet.model.init_mode=uniform\
  nnet.model.architecture=[93,30],[93,70,30],[93,70,50,30]\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogEuclideanMetric\
  nnet.model.beta=0,1/30,1/900,-1/900,-0.03\
  hydra.run.dir=./outputs/10Folds/uniform/HDM05\
  hydra.sweep.dir=./outputs/10Folds/uniform/HDM05

python SPDNet-MLR_Kfolds.py -m\
  dataset=HDM05\
  dataset.path=/data/zchen/Datasets/HDM05/spd_data_1e-6_1000000/\
  fit.folds=10\
  fit.epochs=150\
  fit.cycle=50\
  nnet.model.init_mode=svd\
  nnet.model.architecture=[93,30],[93,70,30],[93,70,50,30]\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogEuclideanMetric\
  nnet.model.beta=0,1/30,1/900,-1/900,-0.03\
  hydra.run.dir=./outputs/10Folds/svd/HDM05\
  hydra.sweep.dir=./outputs/10Folds/svd/HDM05
