#!/bin/bash

conda activate spddsmbn-venv
cd /data/zchen/Released_Code/SPDMLR

#SPDNet
python SPDNet-MLR.py -m\
  dataset=HDM05\
  dataset.path=/data/zchen/Datasets/HDM05/spd_data_1e-6_1000000/\
  nnet.model.architecture=[93,30],[93,70,30],[93,70,50,30]\
  nnet.model.classifier=LogEigMLR

#SPDNet-SPDMLR-LEM
python SPDNet-MLR.py -m\
  dataset=HDM05\
  dataset.path=/data/zchen/Datasets/HDM05/spd_data_1e-6_1000000/\
  nnet.model.architecture=[93,30],[93,70,30],[93,70,50,30]\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogEuclideanMetric\
  nnet.model.beta=0,1.0,1/30,1/900,-1/900,-0.03\

#SPDNet-SPDMLR-LCM
python SPDNet-MLR.py -m\
  dataset=HDM05\
  dataset.path=/data/zchen/Datasets/HDM05/spd_data_1e-6_1000000/\
  nnet.model.architecture=[93,30],[93,70,30],[93,70,50,30]\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogCholeskyMetric\
  nnet.model.power=0.5,1.,1.5

# SPDNet-SPDMLR-LCM
python SPDNet-MLR.py -m\
  dataset=HDM05\
  dataset.path=/data/zchen/Datasets/HDM05/spd_data_1e-6_1000000/\
  nnet.optimizer.mode=AMSGRAD,SGD,ADAM\
  nnet.optimizer.lr=1e-3,2.5e-3,5e-3,1e-2,2.5e-2,5e-2\
  nnet.model.init_mode=uniform\
  nnet.model.architecture=[93,30]\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogCholeskyMetric\
  nnet.model.power=1.\
  hydra.run.dir=outputs/HDM05/LCM\
  hydra.sweep.dir=outputs/HDM05/LCM