#!/bin/bash

conda activate spddsmbn-venv
cd /data/zchen/Released_Code/SPDMLR

#inter-subject+uda,inter-session+uda

#baseline
python TSMNet-MLR.py -m\
  evaluation=inter-session+uda,inter-subject+uda

# --- LEM ----
#inter-session+uda
python TSMNet-MLR.py -m\
  evaluation=inter-session+uda\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogEuclideanMetric\
  nnet.model.power=1\
  nnet.model.beta=-0.0025,-0.04,0.0025,0.05,1.0,0

#inter-subject+uda
python TSMNet-MLR.py -m\
  evaluation=inter-subject+uda\
  nnet.model.classifier=SPDMLR\
  nnet.model.metric=SPDLogEuclideanMetric\
  nnet.model.power=1\
  nnet.model.beta=-0.0025,-0.04,0.0025,0.05,1.0,0
